# Generated by Django 4.1.7 on 2023-06-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="windowstatus",
            old_name="window",
            new_name="windowstatus",
        ),
    ]
