# Generated by Django 4.1.7 on 2023-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_window_windowstatus_windowstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ODFineDust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name="FineDust",
            new_name="IDFineDust",
        ),
    ]
