# Generated by Django 4.1.7 on 2023-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name="rain",
            old_name="rain",
            new_name="rainstatus",
        ),
    ]
